# SPDX-FileCopyrightText: 2021 metaquarx <metaquarx@protonmail.com>
# SPDX-License-Identifier: Apache-2.0

image: alpine

stages:
    - build
    - artifacts

before_script:
    - apk update
    - apk add make cmake g++ binutils build-base git doxygen gcovr

build:
    stage: build
    script:
        - cmake -S . -B build -DSTITCH_BUILD_DOCS=ON -DSTITCH_BUILD_TESTS=ON -DSTITCH_BUILD_COVERAGE=ON
        - cmake --build build
        - ctest --test-dir build/tests
        - gcovr --xml-pretty --exclude-unreachable-branches --print-summary -o build/tests/reports/coverage.xml --root .
    coverage: /^\s*lines:\s*\d+.\d+\%/
    artifacts:
        when: always
        name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
        reports:
            junit: ./build/tests/reports/*.xml
            cobertura: build/tests/reports/coverage.xml
        paths:
            - build/docs/*
            - build/CMakeCache.txt
            - build/Makefile
        expire_in: 2 days

pages:
    stage: artifacts
    needs: ['build']
    script:
        - cmake --build build -t doxygen
        - mv build/docs/html public
    artifacts:
        paths:
            - public/
        expire_in: 2 days
    only:
        - trunk
